"""
Módulo de compatibilidade para LLM Manager.
A lógica foi decomposta em sub-módulos: types, pricing, resilience, factory, router, client.
Este arquivo re-exporta os símbolos públicos para manter a compatibilidade.
"""

from .client import LLM_LATENCY, LLM_REQUESTS, LLM_TOKENS, LLMClient, get_llm_client
from .factory import (
    _get_executor,
    _get_openai_client,
    _health_check_ollama,
    _infer_model_name,
    _infer_provider,
    _validate_gemini_key,
    _validate_openai_key,
    warm_llm_pool,
)
from .pricing import (
    LLM_COST_DEVIATION_USD,
    LLM_EXPECTED_KTOKENS_GAUGE,
    LLM_PROVIDER_BUDGET_REMAINING,
    LLM_PROVIDER_SPEND_USD,
    LLM_TENANT_SPEND_USD,
    _budget_allows,
    _budget_remaining,
    _expected_k_ema_by_role,
    _get_model_pricing,
    _model_penalty_factors,
    _model_stats,
    _provider_budgets_usd,
    _provider_pricing,
    _provider_spend_usd,
    _provider_stats,
    _register_tenant_spend,
    _tenant_budget_remaining,
    _tenant_project_daily_budget_usd,
    _tenant_project_spend_usd,
    _tenant_user_daily_budget_usd,
    _tenant_user_spend_usd,
)
from .resilience import (
    LLM_POOL_EVICTIONS,
    LLM_POOL_HITS,
    LLM_POOL_MISSES,
    LLM_POOL_SIZE,
    LLM_POOL_WARMS,
    _add_to_pool,
    _circuit_closed,
    _get_from_pool,
    _llm_pool,
    _pool_key,
    _provider_circuit_breakers,
    invalidate_cache,
)
from .router import (
    LLM_EXPECTED_COST_USD,
    LLM_EXPLORATION_DECISIONS,
    LLM_MODEL_SELECTION_SCORE,
    LLM_ROUTER_COUNTER,
    LLM_SELECTION_SCORE,
    _normalize,
    get_llm,
)
from .types import CachedLLM, ModelPriority, ModelRole, ModelStats, ProviderPricing, ProviderStats

__all__ = [
    # Types
    "ModelRole",
    "ModelPriority",
    "CachedLLM",
    "ProviderPricing",
    "ProviderStats",
    "ModelStats",
    # Pricing
    "LLM_PROVIDER_SPEND_USD",
    "LLM_PROVIDER_BUDGET_REMAINING",
    "LLM_TENANT_SPEND_USD",
    "LLM_COST_DEVIATION_USD",
    "LLM_EXPECTED_KTOKENS_GAUGE",
    "_provider_stats",
    "_model_stats",
    "_provider_pricing",
    "_provider_budgets_usd",
    "_provider_spend_usd",
    "_model_penalty_factors",
    "_expected_k_ema_by_role",
    "_tenant_user_daily_budget_usd",
    "_tenant_project_daily_budget_usd",
    "_tenant_user_spend_usd",
    "_tenant_project_spend_usd",
    "_budget_remaining",
    "_budget_allows",
    "_get_model_pricing",
    "_tenant_budget_remaining",
    "_register_tenant_spend",
    # Resilience
    "invalidate_cache",
    "LLM_POOL_SIZE",
    "LLM_POOL_HITS",
    "LLM_POOL_MISSES",
    "LLM_POOL_EVICTIONS",
    "LLM_POOL_WARMS",
    "_llm_pool",
    "_provider_circuit_breakers",
    "_circuit_closed",
    "_get_from_pool",
    "_add_to_pool",
    "_pool_key",
    # Factory
    "warm_llm_pool",
    "_get_executor",
    "_get_openai_client",
    "_validate_gemini_key",
    "_validate_openai_key",
    "_health_check_ollama",
    "_infer_provider",
    "_infer_model_name",
    # Router
    "get_llm",
    "LLM_ROUTER_COUNTER",
    "LLM_SELECTION_SCORE",
    "LLM_MODEL_SELECTION_SCORE",
    "LLM_EXPECTED_COST_USD",
    "LLM_EXPLORATION_DECISIONS",
    "_normalize",
    # Client
    "LLMClient",
    "get_llm_client",
    "LLM_REQUESTS",
    "LLM_LATENCY",
    "LLM_TOKENS",
]
