#!/usr/bin/env bash
# PC2 Hardware Performance Tuning Guide
# i9-13900F + 64GB DDR5-5600 + RTX 4060 Ti 16GB

set -e

echo "🚀 PC2 HARDWARE OPTIMIZATION GUIDE"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🖥️  HARDWARE SPECIFICATION"
echo "───────────────────────────────────────────────────────────────"
echo "CPU:    Intel i9-13900F (24 cores: 8 P-cores + 16 E-cores)"
echo "RAM:    64GB DDR5-5600 (dual-channel, high-bandwidth)"
echo "GPU:    NVIDIA RTX 4060 Ti (16GB GDDR6, 152-bit bus)"
echo "Storage: (SSD assumed for Qdrant vector DB)"
echo ""

echo "💾 MEMORY ALLOCATION (64GB total)"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "┌─────────────────────┬──────────┬──────────────────────────┐"
echo "│ Service             │ Allocated│ Purpose                  │"
echo "├─────────────────────┼──────────┼──────────────────────────┤"
echo "│ Neo4j (Heap)        │ 20 GB    │ Graph queries, indexing  │"
echo "│ Neo4j (PageCache)   │ 12 GB    │ Node/relationship cache  │"
echo "│ Qdrant              │ 12 GB    │ Vector search (HNSW)     │"
echo "│ Ollama (RAM)        │ 20 GB    │ Token generation, context│"
echo "│ Ollama (VRAM)       │ 16 GB    │ GPU memory (4060 Ti)     │"
echo "│ System/Buffers      │ ~4 GB    │ Kernel, page tables      │"
echo "├─────────────────────┼──────────┼──────────────────────────┤"
echo "│ TOTAL               │ ~84 GB   │ (includes overhead)      │"
echo "└─────────────────────┴──────────┴──────────────────────────┘"
echo ""

echo "⚡ CPU ALLOCATION (24 cores)"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "P-cores (Performance, 3.0-5.6 GHz):"
echo "  Cores 0-7 (8 total)"
echo "    └─ Neo4j (cores 0-7):        8 cores (consistent, low-latency)"
echo ""
echo "E-cores (Efficiency, 2.5-4.3 GHz):"
echo "  Cores 8-23 (16 total)"
echo "    ├─ Neo4j (cores 8-9):        2 cores"
echo "    ├─ Qdrant (cores 10-15):     6 cores (vector HNSW indexing)"
echo "    └─ Ollama (cores 16-23):     8 cores (token generation)"
echo ""
echo "Usage Pattern:"
echo "  • Neo4j: 10 cores total (P+E mix for low-latency graph ops)"
echo "  • Qdrant: 6 E-cores (HNSW is CPU-bound, E-cores sufficient)"
echo "  • Ollama: 8 E-cores + GPU acceleration"
echo ""

echo "🎮 GPU CONFIGURATION (RTX 4060 Ti)"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Specs:"
echo "  VRAM:        16 GB GDDR6"
echo "  Cores:       2560 CUDA cores"
echo "  Memory Bus:  128-bit (upgraded from 96-bit 4060)"
echo "  Bandwidth:   432 GB/s"
echo ""
echo "Model Capacity (VRAM usage):"
echo "  gpt-oss:20b       ~11 GB (20B parameters)"
echo "  deepseek-coder    ~4-6 GB (6.7B parameters)"
echo "  ministral-3:14b   ~8-9 GB (14B parameters)"
echo ""
echo "Loading Strategy:"
echo "  • Load 2 models max: gpt-oss:20b (11GB) + deepseek-coder (4GB) = 15GB"
echo "  • Keep-alive: 30 minutes (unload after 30min inactivity)"
echo "  • Queue size: 512 (handle bursts without dropping requests)"
echo ""

echo "🔥 PERFORMANCE TUNING"
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "1. Neo4j Optimization:"
echo "   • Heap: 20GB (sufficient for most workloads)"
echo "   • Page Cache: 12GB (buffer graph pages, avoid disk I/O)"
echo "   • Connection Pool: 20-200 threads (auto-scaling)"
echo "   • L3 Cache: 8MB per P-core = 64MB total (utilized by kernel)"
echo ""
echo "   Upgrade path:"
echo "   - More connections? Increase pool: 50-500"
echo "   - More indexing? Increase heap: 25-30GB"
echo "   - Large graphs? Increase page cache: 15-20GB"
echo ""

echo "2. Qdrant Optimization:"
echo "   • Storage: In-memory (not memory-mapped)"
echo "   • HNSW: CPU-optimized nearest neighbor search"
echo "   • Batch size: Auto-optimized per query"
echo ""
echo "   Upgrade path:"
echo "   - Larger vector indexes? Increase memory: 16-24GB"
echo "   - More concurrent queries? Increase cores: 8-10"
echo "   - SSD bottleneck? Enable memory-mapping: PREFER_MMAP=true"
echo ""

echo "3. Ollama Optimization:"
echo "   • Parallel: 1 (sequential inference, no VRAM contention)"
echo "   • Threads: 16 CPU threads (P+E hybrid)"
echo "   • Context: 8192 tokens (balance speed vs capability)"
echo ""
echo "   Upgrade path:"
echo "   - Concurrent inference? Increase parallel: 2 (risk OOM)"
echo "   - Longer contexts? Increase CTX: 16384 (slower)"
echo "   - Batch processing? Use queue: 512+ requests buffered"
echo ""

echo ""
echo "⚙️  CONFIGURATION OPTIONS"
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "AGGRESSIVE MODE (max performance, high resource usage):"
echo ""
echo "  # .env.pc2"
echo "  NEO4J_HEAP_MAX=25G"
echo "  NEO4J_PAGECACHE=15G"
echo "  NEO4J_CPUS=12.0"
echo ""
echo "  QDRANT_MEM_LIMIT=16g"
echo "  QDRANT_CPUS=8.0"
echo ""
echo "  OLLAMA_KEEP_ALIVE=60m"
echo "  OLLAMA_NUM_PARALLEL=2"
echo "  OLLAMA_NUM_THREAD=12"
echo ""
echo "  ⚠️  Risk: May cause swapping if all services peak simultaneously"
echo ""

echo "BALANCED MODE (default, recommended):"
echo ""
echo "  # .env.pc2"
echo "  NEO4J_HEAP_MAX=20G"
echo "  NEO4J_PAGECACHE=12G"
echo "  NEO4J_CPUS=10.0"
echo ""
echo "  QDRANT_MEM_LIMIT=12g"
echo "  QDRANT_CPUS=6.0"
echo ""
echo "  OLLAMA_KEEP_ALIVE=30m"
echo "  OLLAMA_NUM_PARALLEL=1"
echo "  OLLAMA_NUM_THREAD=16"
echo ""
echo "  ✅ Safe: Leaves room for OS and spikes"
echo ""

echo "CONSERVATIVE MODE (stable, predictable):"
echo ""
echo "  # .env.pc2"
echo "  NEO4J_HEAP_MAX=16G"
echo "  NEO4J_PAGECACHE=10G"
echo "  NEO4J_CPUS=8.0"
echo ""
echo "  QDRANT_MEM_LIMIT=10g"
echo "  QDRANT_CPUS=4.0"
echo ""
echo "  OLLAMA_KEEP_ALIVE=10m"
echo "  OLLAMA_NUM_PARALLEL=1"
echo "  OLLAMA_NUM_THREAD=8"
echo ""
echo "  ✅ Stable: Heavy system load OK, slower response times"
echo ""

echo ""
echo "📊 MONITORING COMMANDS"
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "Real-time GPU usage:"
echo "  nvidia-smi dmon -s pucm"
echo ""

echo "Container resource usage:"
echo "  docker stats --no-stream --format 'table {{.Container}}\t{{.MemUsage}}\t{{.CPUPerc}}\t{{.NetIO}}'"
echo ""

echo "Neo4j memory:"
echo "  docker exec janus_neo4j_pc2 curl -s http://localhost:7474/db/neo4j/transactions | jq '.errors'"
echo ""

echo "Qdrant collections (size estimate):"
echo "  curl -H 'api-key: YOUR_KEY' http://localhost:6333/collections"
echo ""

echo "Ollama running models:"
echo "  curl http://localhost:11434/api/tags"
echo ""

echo "CPU affinity verification:"
echo "  docker inspect janus_neo4j_pc2 | grep CpusetCpus"
echo "  docker inspect janus_qdrant_pc2 | grep CpusetCpus"
echo "  docker inspect janus_ollama_pc2 | grep CpusetCpus"
echo ""

echo ""
echo "🚀 STARTUP PERFORMANCE EXPECTATIONS"
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "First-time startup (with model download):"
echo "  • Neo4j initialization:    ~30-60 seconds"
echo "  • Qdrant startup:          ~10-20 seconds"
echo "  • Ollama startup:          ~5-10 seconds"
echo "  • Model download (gpt-oss:20b): ~10-15 minutes (network-dependent)"
echo "  • Total first-run:         ~20-30 minutes"
echo ""

echo "Subsequent startup (models cached):"
echo "  • Neo4j:                   ~30-45 seconds"
echo "  • Qdrant:                  ~10-15 seconds"
echo "  • Ollama (with models):    ~30-60 seconds"
echo "  • Total warm start:        ~2-3 minutes"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✨ Configuration complete! Start with:"
echo ""
echo "  docker compose -f docker-compose.pc2.yml up -d"
echo ""
echo "Monitor with:"
echo ""
echo "  docker compose -f docker-compose.pc2.yml logs -f"
echo "  nvidia-smi dmon -s pucm"
echo "  docker stats --no-stream"
echo ""
